"""Constants for 4-noks integration."""

DOMAIN = "4_noks"

DEFAULT_BRAND = "4-noks"
DEFAULT_HOST = ""
DEFAULT_INTERVAL = 60
DEFAULT_PORT = 5001

TCP_TIMEOUT = 10

CONF_INTERVAL = "interval"
CONF_SERIAL = "SERIAL_NUMBER"
